export const movies = {
    "page":1,
    "total_results":8,
    "total_pages":1,
    "results":
    [
        {
            "vote_count":4,
            "id":199951,
            "video":true,
            "vote_average":9,
            "title":"Quentin Tarantino: 20 Years of Filmmaking",
            "popularity":4.040723,
            "poster_path":"\/bzrTHS1JrC8BJszpqKHGX4rLnoV.jpg",
            "original_language":"en",
            "original_title":"Quentin Tarantino: 20 Years of Filmmaking",
            "genre_ids":[99],
            "backdrop_path":"\/m7HFlgs7zQtMAwPZNpIJy1TZhr8.jpg",
            "adult":false,
            "overview":"Take a look at Tarantino's career from the beginning, with interviews from co-workers, critics, stars and master filmmakers alike as well as a tribute to his greatest collaborator, Sally Menke. Produced for the 'Tarantino XX' Blu-ray collection",
            "release_date":"2012-11-20"
        },
        {
            "vote_count":2,
            "id":102817,
            "video":false,
            "vote_average":5.3,
            "title":"Quentin Tarantino's Star Wars",
            "popularity":1.084935,
            "poster_path":"\/5jbEXq7SmyahaYWHQoyO6HVUPjj.jpg",
            "original_language":"en",
            "original_title":"Quentin Tarantino's Star Wars",
            "genre_ids":[16],
            "backdrop_path":"\/a61gR0hrF1dcBJqw7m45q1TTh87.jpg",
            "adult":false,
            "overview":"We're all familiar with the story: a long time ago in a galaxy far, far away, on a planet called Tattooine, a boy named Luke Skywalker is adopted by the only remaining Jedi knight and helps the Rebellion destroy the Death Star after learning the ways of the force. However, what if \"Pulp Fiction\" director Quentin Tarantino had directed George Lucas' script, using Kenner action figures and stop computer animation?",
            "release_date":"2002-06-09"
        },
        {
            "vote_count":4,
            "id":199651,
            "video":true,
            "vote_average":9,
            "title":"Quentin Tarantino: 20 Years of Filmmaking",
            "popularity":4.040723,
            "poster_path":"\/bzrTHS1JrC8BJszpqKHGX4rLnoV.jpg",
            "original_language":"en",
            "original_title":"Quentin Tarantino: 20 Years of Filmmaking",
            "genre_ids":[99],
            "backdrop_path":"\/m7HFlgs7zQtMAwPZNpIJy1TZhr8.jpg",
            "adult":false,
            "overview":"Take a look at Tarantino's career from the beginning, with interviews from co-workers, critics, stars and master filmmakers alike as well as a tribute to his greatest collaborator, Sally Menke. Produced for the 'Tarantino XX' Blu-ray collection",
            "release_date":"2012-11-20"
        },
        {
            "vote_count":2,
            "id":402817,
            "video":false,
            "vote_average":5.3,
            "title":"Quentin Tarantino's Star Wars",
            "popularity":1.084935,
            "poster_path":"\/5jbEXq7SmyahaYWHQoyO6HVUPjj.jpg",
            "original_language":"en",
            "original_title":"Quentin Tarantino's Star Wars",
            "genre_ids":[16],
            "backdrop_path":"\/a61gR0hrF1dcBJqw7m45q1TTh87.jpg",
            "adult":false,
            "overview":"We're all familiar with the story: a long time ago in a galaxy far, far away, on a planet called Tattooine, a boy named Luke Skywalker is adopted by the only remaining Jedi knight and helps the Rebellion destroy the Death Star after learning the ways of the force. However, what if \"Pulp Fiction\" director Quentin Tarantino had directed George Lucas' script, using Kenner action figures and stop computer animation?",
            "release_date":"2002-06-09"
        },
        {
            "vote_count":4,
            "id":199551,
            "video":true,
            "vote_average":9,
            "title":"Quentin Tarantino: 20 Years of Filmmaking",
            "popularity":4.040723,
            "poster_path":"\/bzrTHS1JrC8BJszpqKHGX4rLnoV.jpg",
            "original_language":"en",
            "original_title":"Quentin Tarantino: 20 Years of Filmmaking",
            "genre_ids":[99],
            "backdrop_path":"\/m7HFlgs7zQtMAwPZNpIJy1TZhr8.jpg",
            "adult":false,
            "overview":"Take a look at Tarantino's career from the beginning, with interviews from co-workers, critics, stars and master filmmakers alike as well as a tribute to his greatest collaborator, Sally Menke. Produced for the 'Tarantino XX' Blu-ray collection",
            "release_date":"2012-11-20"
        },
        {
            "vote_count":2,
            "id":102717,
            "video":false,
            "vote_average":5.3,
            "title":"Quentin Tarantino's Star Wars",
            "popularity":1.084935,
            "poster_path":"\/5jbEXq7SmyahaYWHQoyO6HVUPjj.jpg",
            "original_language":"en",
            "original_title":"Quentin Tarantino's Star Wars",
            "genre_ids":[16],
            "backdrop_path":"\/a61gR0hrF1dcBJqw7m45q1TTh87.jpg",
            "adult":false,
            "overview":"We're all familiar with the story: a long time ago in a galaxy far, far away, on a planet called Tattooine, a boy named Luke Skywalker is adopted by the only remaining Jedi knight and helps the Rebellion destroy the Death Star after learning the ways of the force. However, what if \"Pulp Fiction\" director Quentin Tarantino had directed George Lucas' script, using Kenner action figures and stop computer animation?",
            "release_date":"2002-06-09"
        },
        {
            "vote_count":4,
            "id":189951,
            "video":true,
            "vote_average":9,
            "title":"Quentin Tarantino: 20 Years of Filmmaking",
            "popularity":4.040723,
            "poster_path":"\/bzrTHS1JrC8BJszpqKHGX4rLnoV.jpg",
            "original_language":"en",
            "original_title":"Quentin Tarantino: 20 Years of Filmmaking",
            "genre_ids":[99],
            "backdrop_path":"\/m7HFlgs7zQtMAwPZNpIJy1TZhr8.jpg",
            "adult":false,
            "overview":"Take a look at Tarantino's career from the beginning, with interviews from co-workers, critics, stars and master filmmakers alike as well as a tribute to his greatest collaborator, Sally Menke. Produced for the 'Tarantino XX' Blu-ray collection",
            "release_date":"2012-11-20"
        },
        {
            "vote_count":2,
            "id":101817,
            "video":false,
            "vote_average":5.3,
            "title":"Quentin Tarantino's Star Wars",
            "popularity":1.084935,
            "poster_path":"\/5jbEXq7SmyahaYWHQoyO6HVUPjj.jpg",
            "original_language":"en",
            "original_title":"Quentin Tarantino's Star Wars",
            "genre_ids":[16],
            "backdrop_path":"\/a61gR0hrF1dcBJqw7m45q1TTh87.jpg",
            "adult":false,
            "overview":"We're all familiar with the story: a long time ago in a galaxy far, far away, on a planet called Tattooine, a boy named Luke Skywalker is adopted by the only remaining Jedi knight and helps the Rebellion destroy the Death Star after learning the ways of the force. However, what if \"Pulp Fiction\" director Quentin Tarantino had directed George Lucas' script, using Kenner action figures and stop computer animation?",
            "release_date":"2002-06-09"
        },
        {
            "vote_count":4,
            "id":199051,
            "video":true,
            "vote_average":9,
            "title":"Quentin Tarantino: 20 Years of Filmmaking",
            "popularity":4.040723,
            "poster_path":"\/bzrTHS1JrC8BJszpqKHGX4rLnoV.jpg",
            "original_language":"en",
            "original_title":"Quentin Tarantino: 20 Years of Filmmaking",
            "genre_ids":[99],
            "backdrop_path":"\/m7HFlgs7zQtMAwPZNpIJy1TZhr8.jpg",
            "adult":false,
            "overview":"Take a look at Tarantino's career from the beginning, with interviews from co-workers, critics, stars and master filmmakers alike as well as a tribute to his greatest collaborator, Sally Menke. Produced for the 'Tarantino XX' Blu-ray collection",
            "release_date":"2012-11-20"
        },
        {
            "vote_count":2,
            "id":16817,
            "video":false,
            "vote_average":5.3,
            "title":"Quentin Tarantino's Star Wars",
            "popularity":1.084935,
            "poster_path":"\/5jbEXq7SmyahaYWHQoyO6HVUPjj.jpg",
            "original_language":"en",
            "original_title":"Quentin Tarantino's Star Wars",
            "genre_ids":[16],
            "backdrop_path":"\/a61gR0hrF1dcBJqw7m45q1TTh87.jpg",
            "adult":false,
            "overview":"We're all familiar with the story: a long time ago in a galaxy far, far away, on a planet called Tattooine, a boy named Luke Skywalker is adopted by the only remaining Jedi knight and helps the Rebellion destroy the Death Star after learning the ways of the force. However, what if \"Pulp Fiction\" director Quentin Tarantino had directed George Lucas' script, using Kenner action figures and stop computer animation?",
            "release_date":"2002-06-09"
        },
        {
            "vote_count":4,
            "id":19451,
            "video":true,
            "vote_average":9,
            "title":"Quentin Tarantino: 20 Years of Filmmaking",
            "popularity":4.040723,
            "poster_path":"\/bzrTHS1JrC8BJszpqKHGX4rLnoV.jpg",
            "original_language":"en",
            "original_title":"Quentin Tarantino: 20 Years of Filmmaking",
            "genre_ids":[99],
            "backdrop_path":"\/m7HFlgs7zQtMAwPZNpIJy1TZhr8.jpg",
            "adult":false,
            "overview":"Take a look at Tarantino's career from the beginning, with interviews from co-workers, critics, stars and master filmmakers alike as well as a tribute to his greatest collaborator, Sally Menke. Produced for the 'Tarantino XX' Blu-ray collection",
            "release_date":"2012-11-20"
        },
        {
            "vote_count":2,
            "id":10237,
            "video":false,
            "vote_average":5.3,
            "title":"Quentin Tarantino's Star Wars",
            "popularity":1.084935,
            "poster_path":"\/5jbEXq7SmyahaYWHQoyO6HVUPjj.jpg",
            "original_language":"en",
            "original_title":"Quentin Tarantino's Star Wars",
            "genre_ids":[16],
            "backdrop_path":"\/a61gR0hrF1dcBJqw7m45q1TTh87.jpg",
            "adult":false,
            "overview":"We're all familiar with the story: a long time ago in a galaxy far, far away, on a planet called Tattooine, a boy named Luke Skywalker is adopted by the only remaining Jedi knight and helps the Rebellion destroy the Death Star after learning the ways of the force. However, what if \"Pulp Fiction\" director Quentin Tarantino had directed George Lucas' script, using Kenner action figures and stop computer animation?",
            "release_date":"2002-06-09"
        }
    ]
};

export const movie = {
    "adult":false,
    "backdrop_path":"/m7HFlgs7zQtMAwPZNpIJy1TZhr8.jpg",
    "belongs_to_collection":null,
    "budget":0,
    "genres":[{
        "id":99,
        "name":"Documentary"
    }],
    "homepage":"",
    "id":199951,
    "imdb_id":"tt6021960",
    "original_language":"en",
    "original_title":"Quentin Tarantino: 20 Years of Filmmaking",
    "overview":"Take a look at Tarantino's career from the beginning, with interviews from co-workers, critics, stars and master filmmakers alike as well as a tribute to his greatest collaborator, Sally Menke. Produced for the 'Tarantino XX' Blu-ray collection",
    "popularity":1.584108,
    "poster_path":"/bzrTHS1JrC8BJszpqKHGX4rLnoV.jpg",
    "production_companies":[],
    "production_countries":[{
        "iso_3166_1":"US",
        "name":"United States of America"
    }],
    "release_date":"2012-11-20",
    "revenue":0,
    "runtime":133,
    "spoken_languages":[{
        "iso_639_1":"en",
        "name":"English"
    }],
    "status":"Released",
    "tagline":"",
    "title":"Quentin Tarantino: 20 Years of Filmmaking",
    "video":true,
    "vote_average":9.0,
    "vote_count":4
};